### ISSUE TITLE
Test Email working but not actual emails

### ISSUE THREAD

**Issue by scmartinez** [samuelaguilera/sar-friendly-smtp#10]
We have set up the SMTP server details but when users send emails they are coming from a specific user (the admin who set up the plugin) and NOT the From field settings or SMTP server details settings.

**Comment by samuelaguilera** [comment]
As explained in the settings the From Adress email specified in settings is only used when outgoing original message uses default value: wordpress@yourdomain.com

According to your description of the issue a third-party in your site is customizing the from address for the email. So it's expected to not see the email you added in the settings replacing that email set by the third-party, as this is one of the key features of this SMTP plugin.

If you want to replace the from email address in all your outgoing emails at all cost, I would recommend you to use any of the SMTP plugins available that do that.

**Comment by scmartinez** [comment]
Got it! Fixed! Thanks
