### ISSUE TITLE
WordPress was not able to pass the email to the SMTP server.  Error returned by PHPMailer class: SMTP Error: The following recipients failed: rhys@oxfordtefl.com: : Sender address rejected: not owned by user uek266c 

### ISSUE THREAD

**Issue by MrBonney86** [samuelaguilera/sar-friendly-smtp#12]
Hi, I am getting this error. I do not know who user uek266c is.

Any help please?

**Comment by samuelaguilera** [comment]
This is not an error in the plugin, it's an error returned by your SMTP server. You will want to contact with your SMTP server support for assistance.

**Comment by MrBonney86** [comment]
Thanks, all sorted now.
