### ISSUE TITLE
Sending Mail From A Multisite Subdirectory Site | Mail Received Shows From Primary Domain

### ISSUE THREAD

**Issue by InstallationComplete** [samuelaguilera/sar-friendly-smtp#13]
Hello,

I'm sending mail using mailgun on a subdomain. I tried with SAR Friendly SMTP both network activated and activated only on a single subdomain. When sending tests, all emails when received show being sent from the Primary Domain, never the Subdomain.

Any suggestions or insight?

**Comment by samuelaguilera** [comment]
The plugin only sets, optionally, the **From Name** and **From Address** (as configured in the plugin settings), any other information in the email is **not controlled by the plugin**.

**Comment by InstallationComplete** [comment]
I'm not sure why you closed the topic. Anyways. That is the exact issue. **The plugin is not using the From Name of the Subsite.** It's using the From name of the Primary site.

**Comment by samuelaguilera** [comment]
From Name is only replaced when default **WordPress** is used, this is a main feature of the plugin, if you're receiving the email with any other From Name then the plugin is working as expected. There are many other plugins outhere that you can use to replace the From Name always.

**Comment by InstallationComplete** [comment]
I think you're not understanding the issue or I'm not understanding something. The plugin is sending emails from a subsite using the primary domain From Name.

**Primary Domain:**
abc.com = ABC

**Subsite Domain:**
xyz.com = XYZ

Sending admin emails from xyz.com are being sent as with ABC as the From.
