### ISSUE TITLE
Hijacking Gravity Forms From Field

### ISSUE THREAD

**Issue by jacobdubail** [samuelaguilera/sar-friendly-smtp#2]
Howdy,

Your plugin is working great except for one piece. Our Gravity Forms Admin Notification uses the user submitted email address as the From email to make replying to the customer easier for our support team. Strangely, the From Name isn't hijacked, only the From Email.

Any tips?
Thanks!

**Comment by samuelaguilera** [comment]
Hi,

Can you provide a screenshot of the sar-friendly-smtp from settings section and also the same for your GF notification?

Regards.
