### ISSUE TITLE
Return-Path not being written when is wordpress@...

### ISSUE THREAD

**Issue by YbyMMbPh** [samuelaguilera/sar-friendly-smtp#3]
For about a week or two many of my SAR emails are not being delivered.
WordPress update emails are not being accepted by exim.
SAR "Send test email" are not being accepted by exim.
I think it may have coincided with WP 4.6.
I tracked the problem to my server not accepting emails from non-existent users.
A SAR "Send test email" returns this error...

```
Error returned by PHPMailer class:
SMTP Error: The following recipients failed: validuser@domain.com:
Verification failed for No Such User Here" Sender verify failed
```

I turned off Sender Verification on the server. Log output...

```
Updating “Sender Verification” from “On” to “Off”.
“Sender Verification” was updated.
```

Now the emails are accepted and I can see the problem in the Headers.
The Return-Path is..
Return-Path: wordpress@domain.com

This is new.
SAR used to produce
Return-Path: authenicated-email@domain.com

So... Samuel could you please test this for yourself and confirm (or reject) this problem.

**Comment by samuelaguilera** [comment]
Hi!

The plugin doesn't handle the return-path or sender information, that is totally handled by WordPress.

If you have noticed this issue after upgrading to WP 4.6, you're probably affected by a bug introduced in WP 4.6 [described on this ticket from WP core trac](https://core.trac.wordpress.org/ticket/37736). They have already [a patch for the bug](https://core.trac.wordpress.org/changeset/38286/trunk/src/wp-includes/pluggable.php).

Regards.
