### ISSUE TITLE
Feature request: send test message

### ISSUE THREAD

**Issue by mathuaerknedam** [samuelaguilera/sar-friendly-smtp#5]
Thanks for a simple tool, I appreciate it. That said, I would like to suggest a small complication.

It took a bit of experimentation to get this working, but I did eventually succeed. I tested my settings by creating new users, which was a bit tedious. It would have been really helpful if this plugin provided a way to send a test message. Ideally, the interface would also display any debug/log messages relevant to the test message rather than requiring me to enable debug and go check the log.

**Comment by samuelaguilera** [comment]
The plugin already has a test email feature, it's explained in the top of the settings page before any other thing.

**Comment by mathuaerknedam** [comment]
Dang, you're right. I'm sorry about that.
