### ISSUE TITLE
Not working in newest release of Gravity Forms

### ISSUE THREAD

**Issue by RichardX720** [samuelaguilera/sar-friendly-smtp#9]
Good Day, the logs in Gravity Forms states the following:

2017-08-14 19:22:48.920948 - DEBUG --> GFCommon::send_email(): Result from wp_mail(): 1 
2017-08-14 19:22:48.921073 - DEBUG --> GFCommon::send_email(): Mail was passed from WordPress to the mail server. 
2017-08-14 19:22:48.921152 - DEBUG --> GFCommon::send_email(): The WordPress phpmailer_init hook has been detected, usually used by SMTP plugins, it can impact mail delivery.

**Comment by samuelaguilera** [comment]
Hi Richard,

What the Gravity Forms log is telling you is that using a SMTP server can impact delivery not the plugin itself. SAR Friendly SMTP just connect your site with your SMTP server, it doesn't send the email, the email is sent by your SMTP server.

In fact SAR Friendly SMTP was developed to ensure 100% compatibility with Gravity Forms and the Result from wp_mail(): 1 indicates the server reported the email as sent. So from a SAR Friendly SMTP side of things there's not any issue here, the plugin is doing its job as the connection between your WP and your SMTP server is working.

You will want to contact with your SMTP support staff for further assistance. You can also enable the Debug Mode in SAR Friendly SMTP Miscellaneous Settings to monitor the communication between your WP site and your SMTP server, that can provide you more information about what's going behind the scenes.
